### PR TITLE
Better Link Handling

### PR DESCRIPTION
**Pull request by jonsch318**
Changes:
- build script for linux
- A unified link handler:
  - If ctrl is pressed: Open new Tab
  - If shift is pressed: Try to replace the current popup if possible
  - Else replace the tab.
  - If openInNewTab option is selected: Flip ctrl logik: Replace current on ctrl and replace else
- Always click on the first link with ctrl,shift keys on the input field.
- Add vim keyshortcuts "j" for down "k" for up.

### CODE REVIEW

**Comment by Rc-Cookie** [comment]
Nothing against Vim bindings, but isn't that going to prevent you from writing j and k as search query?

**Comment by jonsch318** [comment]
Valid Point.

**Comment by jonsch318** [comment]
I removed vim binding. Could have said ctrl + j or ctrl + k but then its easier to just use arrow keys

**Comment by Rc-Cookie** [comment]
I've added your unified link handling logic and the always-click-on-enter logic to the main branch which is in the process of being published. I also added the Linux build script.

I will, however, not merge this merge request itself, mainly because there are tons of changes because you are using a different formatter. I hope you don't mind. Additionally, I have made some slight modifications in some places:

  - I removed / didn't add the `--override-dest` to the build script(s), I omitted that option on purpose. I did however add a `"$@"` in that place so you can just run `build --override-dest` or equivalently `build -o` to achieve the same result.
  - Middle mouse click (aux click with button 1) does not do the same as left click - it traditionally opens the result in a new tab. I slightly modified your `linkAction` function by adding a `flip` flag which, identically to setting the option in the settings, flips the open in same and open in new tab logic, and is set when something is clicked with the middle mouse button. (I also considered just changing the value passed for the ctrl key, but this way it's better if one later wants to change what to do when you hold the ctrl key)
  - I fixed that pressing enter or space while focusing some course is supposed to click it (you removed it, but it was already broken before which is likely why you did remove it)
  - I fixed that you couldn't hold ctrl or shift and then press enter or space, because pressing any key focuses the search bar (that bug was already present before - I thought I'd fix it now as well)
  - I added a `// Chrome: const canOptnEmbeddedTab = false;` comment behind the corresponding line for the chrome porter to replace it properly

**Comment by jonsch318** [comment]
Fine fine. Although can you put a .eslintrc file so the formatter is the same.

**Pull request closed without merging**
